# Generated by Django 3.1.2 on 2021-05-02 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GachaTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='ガチャタイトル')),
                ('image', models.ImageField(default='paiza.png', upload_to='images/', verbose_name='タイトル画像')),
            ],
            options={
                'verbose_name': 'ガチャタイトル',
                'verbose_name_plural': 'ガチャタイトル',
            },
        ),
        migrations.CreateModel(
            name='GachaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='キャラクター名')),
                ('image', models.ImageField(default='paiza.png', upload_to='images/', verbose_name='アイテム画像')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gacha.gachatitle', verbose_name='ガチャタイトル')),
            ],
            options={
                'verbose_name': 'ガチャアイテム',
                'verbose_name_plural': 'ガチャアイテム',
            },
        ),
    ]
