# Generated by Django 3.1.7 on 2021-05-04 02:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0002_mygachaitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='counter',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='ガチャカウント'),
        ),
    ]
