# Generated by Django 3.1.2 on 2021-05-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0002_gachaitem_rare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='ユーザー名')),
                ('counter', models.IntegerField(default=0, verbose_name='ガチャカウント')),
            ],
            options={
                'verbose_name': 'ガチャカウンター',
                'verbose_name_plural': 'ガチャカウンター',
            },
        ),
    ]
