# Generated by Django 3.1.7 on 2021-04-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='admin', max_length=100, verbose_name='ユーザー名')),
                ('image', models.ImageField(default='skill/images/paiza.png', upload_to='skill/images/', verbose_name='画像')),
            ],
            options={
                'verbose_name': '画像',
                'verbose_name_plural': '画像',
            },
        ),
        migrations.CreateModel(
            name='SkillCheckData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='ユーザー名')),
                ('question_number', models.CharField(max_length=20, verbose_name='問題番号')),
                ('question_level', models.CharField(max_length=1, verbose_name='問題レベル')),
                ('answer_time', models.CharField(max_length=20, verbose_name='回答時間')),
                ('score', models.IntegerField(default=0, verbose_name='点数')),
            ],
            options={
                'verbose_name': '画像データ',
                'verbose_name_plural': '画像データ',
            },
        ),
    ]
