# Generated by Django 3.1.7 on 2021-04-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='paiza.png', upload_to='', verbose_name='画像'),
        ),
    ]
