# Generated by Django 3.1.7 on 2021-04-06 10:19

from django.db import migrations, models
import skill.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_auto_20210406_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='paiza.png', upload_to=skill.models.translate, verbose_name='画像'),
        ),
    ]
